import React from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ArrowRight, Sparkles, CheckCircle, Star, Users, Zap, Target, Rocket, Brain, Shield } from 'lucide-react';
import { Link } from 'react-router-dom';

const LandingPage = () => {
  const features = [
    {
      icon: <Brain className="h-8 w-8 text-green-400" />,
      title: "AI-Powered Idea Generation",
      description: "Transform your thoughts into validated startup concepts with our advanced AI engine."
    },
    {
      icon: <Target className="h-8 w-8 text-emerald-400" />,
      title: "Market Validation",
      description: "Get instant feedback on your ideas with comprehensive market analysis and competitor research."
    },
    {
      icon: <Rocket className="h-8 w-8 text-teal-400" />,
      title: "MVP Development",
      description: "Build your minimum viable product with AI-generated code, templates, and no-code solutions."
    },
    {
      icon: <Users className="h-8 w-8 text-cyan-400" />,
      title: "Team Collaboration",
      description: "Work seamlessly with co-founders and team members in a unified workspace."
    },
    {
      icon: <Zap className="h-8 w-8 text-blue-400" />,
      title: "Investor Ready Docs",
      description: "Generate professional pitch decks, business plans, and investor documents in minutes."
    },
    {
      icon: <Shield className="h-8 w-8 text-violet-400" />,
      title: "Secure & Private",
      description: "Your ideas are protected with enterprise-grade security and privacy controls."
    }
  ];

  const pricingPlans = [
    {
      name: "Free",
      price: "$0",
      period: "forever",
      description: "Perfect for exploring ideas",
      features: [
        "5 AI-generated ideas per month",
        "Basic market validation",
        "Simple pitch outline",
        "Community access"
      ],
      popular: false
    },
    {
      name: "Startup",
      price: "$29",
      period: "per month",
      description: "Everything you need to launch",
      features: [
        "Unlimited AI ideas",
        "Advanced market analysis",
        "Complete pitch deck generation",
        "MVP templates & code",
        "Team collaboration (up to 5 members)",
        "Priority support"
      ],
      popular: true
    },
    {
      name: "Scale",
      price: "$99",
      period: "per month",
      description: "For growing startups",
      features: [
        "Everything in Startup",
        "Unlimited team members",
        "Custom AI training",
        "API access",
        "Dedicated success manager",
        "White-label options"
      ],
      popular: false
    }
  ];

  const testimonials = [
    {
      name: "Sarah Chen",
      role: "Founder, TechFlow",
      content: "PromptHeroReady helped me validate my SaaS idea and build an MVP in just 2 weeks. The AI insights were incredibly accurate.",
      rating: 5
    },
    {
      name: "Marcus Rodriguez",
      role: "CEO, GreenTech Solutions",
      content: "The investor deck generated by this platform got us our seed funding. It's like having a co-founder who never sleeps.",
      rating: 5
    },
    {
      name: "Emily Watson",
      role: "Product Manager, InnovateLab",
      content: "From idea to prototype in record time. The market validation features saved us months of research.",
      rating: 5
    }
  ];

  return (
    <div className="min-h-screen bg-green-glass overflow-hidden">
      {/* Navigation */}
      <nav className="workspace-nav-enhanced">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Sparkles className="h-8 w-8 text-green-400" />
              <span className="text-2xl font-bold text-white">PromptHeroReady</span>
            </div>
            <div className="hidden md:flex items-center gap-6">
              <a
                href="#features"
                className="text-gray-300 hover:text-white transition-colors cursor-pointer"
                onClick={(e) => {
                  e.preventDefault();
                  document.getElementById('features')?.scrollIntoView({ behavior: 'smooth' });
                }}
              >
                Features
              </a>
              <a
                href="#pricing"
                className="text-gray-300 hover:text-white transition-colors cursor-pointer"
                onClick={(e) => {
                  e.preventDefault();
                  document.getElementById('pricing')?.scrollIntoView({ behavior: 'smooth' });
                }}
              >
                Pricing
              </a>
              <a
                href="#testimonials"
                className="text-gray-300 hover:text-white transition-colors cursor-pointer"
                onClick={(e) => {
                  e.preventDefault();
                  document.getElementById('testimonials')?.scrollIntoView({ behavior: 'smooth' });
                }}
              >
                Reviews
              </a>
              <Button asChild variant="outline" className="border-white/20 text-white hover:bg-white/10">
                <Link to="/auth">Sign In</Link>
              </Button>
              <Button asChild className="bg-green-600 hover:bg-green-500">
                <Link to="/auth">Get Started</Link>
              </Button>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-20 pb-32 relative">
        <div className="container mx-auto px-6 text-center">
          <div className="max-w-4xl mx-auto">
            <Badge className="mb-6 bg-green-500/20 text-green-400 border-green-500/30">
              <Sparkles className="h-4 w-4 mr-2" />
              AI-Powered Startup Platform
            </Badge>
            
            <h1 className="text-5xl md:text-7xl font-bold text-white mb-6 leading-tight">
              Turn Your <span className="text-gradient">Ideas</span> Into 
              <br />Successful <span className="text-gradient">Startups</span>
            </h1>
            
            <p className="text-xl text-gray-300 mb-8 max-w-2xl mx-auto">
              The ultimate AI-powered platform for founders. From idea validation to MVP development, 
              we provide everything you need to build and launch your startup faster than ever.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
              <Button asChild size="lg" className="bg-green-600 hover:bg-green-500 text-lg px-8 py-4">
                <Link to="/auth">
                  Start Building Now
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg" className="border-white/20 text-white hover:bg-white/10 text-lg px-8 py-4">
                <Link to="#features">
                  Explore Features
                </Link>
              </Button>
            </div>
            
            <div className="flex items-center justify-center gap-8 text-sm text-gray-400">
              <div className="flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-green-400" />
                <span>No credit card required</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-green-400" />
                <span>14-day free trial</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-green-400" />
                <span>Cancel anytime</span>
              </div>
            </div>
          </div>
        </div>
        
        {/* Decorative elements */}
        <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none">
          <div className="absolute top-20 -left-40 w-96 h-96 bg-green-600/20 rounded-full filter blur-3xl"></div>
          <div className="absolute top-40 -right-40 w-96 h-96 bg-emerald-600/10 rounded-full filter blur-3xl"></div>
          <div className="absolute bottom-20 left-1/2 transform -translate-x-1/2 w-96 h-96 bg-teal-600/15 rounded-full filter blur-3xl"></div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-20">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
              Everything You Need to <span className="text-gradient">Succeed</span>
            </h2>
            <p className="text-xl text-gray-300 max-w-2xl mx-auto">
              Our comprehensive platform provides all the tools and insights you need to transform your ideas into thriving businesses.
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <Card key={index} className={`workspace-card hover:scale-105 transition-all duration-300 ${index % 2 === 0 ? 'feature-gradient-1' : 'feature-gradient-2'}`}>
                <CardHeader>
                  <div className="mb-4">{feature.icon}</div>
                  <CardTitle className="text-white">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-gray-300 text-base">
                    {feature.description}
                  </CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="py-20">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
              Simple, <span className="text-gradient">Transparent</span> Pricing
            </h2>
            <p className="text-xl text-gray-300 max-w-2xl mx-auto">
              Choose the plan that fits your startup journey. Start free and scale as you grow.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {pricingPlans.map((plan, index) => (
              <Card key={index} className={`workspace-card relative ${plan.popular ? 'pricing-card-popular border-green-500/50' : ''} hover:scale-105 transition-all duration-300`}>
                {plan.popular && (
                  <div className="absolute -top-4 left-1/2 transform -translate-x-1/2">
                    <Badge className="bg-green-600 text-white px-4 py-1">
                      Most Popular
                    </Badge>
                  </div>
                )}
                <CardHeader className="text-center">
                  <CardTitle className="text-white text-2xl">{plan.name}</CardTitle>
                  <CardDescription className="text-gray-300">{plan.description}</CardDescription>
                  <div className="mt-4">
                    <span className="text-4xl font-bold text-white">{plan.price}</span>
                    <span className="text-gray-400 ml-2">{plan.period}</span>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  <ul className="space-y-3">
                    {plan.features.map((feature, idx) => (
                      <li key={idx} className="flex items-start gap-3">
                        <CheckCircle className="h-5 w-5 text-green-400 mt-0.5 flex-shrink-0" />
                        <span className="text-gray-300">{feature}</span>
                      </li>
                    ))}
                  </ul>
                  <Button asChild className={`w-full mt-6 ${plan.popular ? 'bg-green-600 hover:bg-green-500' : 'bg-gray-700 hover:bg-gray-600'}`}>
                    <Link to="/auth">
                      {plan.price === "$0" ? "Get Started Free" : "Start Free Trial"}
                    </Link>
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section id="testimonials" className="py-20">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
              Loved by <span className="text-gradient">Founders</span> Worldwide
            </h2>
            <p className="text-xl text-gray-300 max-w-2xl mx-auto">
              Join thousands of successful entrepreneurs who have built their startups with PromptHeroReady.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <Card key={index} className={`workspace-card ${index % 3 === 0 ? 'feature-gradient-1' : index % 3 === 1 ? 'feature-gradient-2' : 'feature-gradient-3'}`}>
                <CardContent className="pt-6">
                  <div className="flex mb-4">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <Star key={i} className="h-5 w-5 text-yellow-400 fill-current" />
                    ))}
                  </div>
                  <p className="text-gray-300 mb-6 italic">"{testimonial.content}"</p>
                  <div>
                    <p className="text-white font-semibold">{testimonial.name}</p>
                    <p className="text-gray-400 text-sm">{testimonial.role}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20">
        <div className="container mx-auto px-6 text-center">
          <div className="max-w-3xl mx-auto workspace-card hero-gradient p-12">
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
              Ready to Build Your <span className="text-gradient">Dream Startup</span>?
            </h2>
            <p className="text-xl text-gray-300 mb-8">
              Join thousands of founders who are already building the future with PromptHeroReady.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button asChild size="lg" className="bg-green-600 hover:bg-green-500 text-lg px-8 py-4">
                <Link to="/auth">
                  Start Your Journey
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg" className="border-white/20 text-white hover:bg-white/10 text-lg px-8 py-4">
                <Link to="/auth">
                  Try Free for 14 Days
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 border-t border-white/10">
        <div className="container mx-auto px-6">
          <div className="flex flex-col md:flex-row items-center justify-between">
            <div className="flex items-center gap-2 mb-4 md:mb-0">
              <Sparkles className="h-6 w-6 text-green-400" />
              <span className="text-xl font-bold text-white">PromptHeroReady</span>
            </div>
            <div className="flex items-center gap-6 text-gray-400">
              <a href="#" className="hover:text-white transition-colors">Privacy</a>
              <a href="#" className="hover:text-white transition-colors">Terms</a>
              <a href="#" className="hover:text-white transition-colors">Support</a>
            </div>
          </div>
          <div className="mt-8 pt-8 border-t border-white/10 text-center text-gray-400">
            <p>&copy; 2024 PromptHeroReady. All rights reserved. Built for founders, by founders.</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
